# Generated by Django 3.1.3 on 2020-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shorturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_query', models.CharField(max_length=8, unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
