# Generated by Django 3.1.3 on 2020-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='local_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
