# Generated by Django 3.1.3 on 2020-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlhandler', '0002_shorturl_local_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='local_ip',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_query',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
